// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGjq7FPm9cB8dh4eEtPaAlyDEGoXcAfig',
    appId: '1:714138207287:web:bbd92a16f5fac6922a6bb2',
    messagingSenderId: '714138207287',
    projectId: 'authenticatorapp-c67e4',
    authDomain: 'authenticatorapp-c67e4.firebaseapp.com',
    storageBucket: 'authenticatorapp-c67e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ_25lUjyN2kqL1Wn8qdLOWXj1LYZLuk8',
    appId: '1:714138207287:android:4fc88734f3cbe9a22a6bb2',
    messagingSenderId: '714138207287',
    projectId: 'authenticatorapp-c67e4',
    storageBucket: 'authenticatorapp-c67e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUEzfmllzhA18gsRRlZnSJ7lm1wDz31DI',
    appId: '1:714138207287:ios:d23ef37dd02369672a6bb2',
    messagingSenderId: '714138207287',
    projectId: 'authenticatorapp-c67e4',
    storageBucket: 'authenticatorapp-c67e4.firebasestorage.app',
    iosBundleId: 'com.example.authenticationapp',
  );
}
